apiVersion: v1
kind: Template
metadata:
  name: jira-chat-notifier
  annotations:
    description: "JIRA Chat Notifier"
    tags: "vshn,jira,chat,slack,rocketchat"
parameters:
- name: URL
  required: true
- name: APP_STAGE
  required: true
- name: APP_IMAGE
  required: true
- name: OPENSHIFT_PROJECT
  required: true
- name: CI_PROJECT_PATH_SLUG
  required: true
- name: CI_ENVIRONMENT_SLUG
  required: true
- name: CI_COMMIT_SHA
  required: true
- name: TLS_ACME
  required: true
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${CI_PROJECT_PATH_SLUG}-${APP_STAGE}
    labels:
      app: ${CI_ENVIRONMENT_SLUG}
      deploymentconfig: ${CI_PROJECT_PATH_SLUG}-${APP_STAGE}
  spec:
    replicas: 1
    selector:
      deploymentconfig: ${CI_PROJECT_PATH_SLUG}-${APP_STAGE}
    strategy:
      type: Rolling
      rollingParams:
        timeoutSeconds: 20
      resources: {}
      activeDeadlineSeconds: 21600
    template:
      metadata:
        labels:
          app: ${CI_ENVIRONMENT_SLUG}
          deploymentconfig: ${CI_PROJECT_PATH_SLUG}-${APP_STAGE}
        annotations:
          ci-commit-sha: ${CI_COMMIT_SHA}
      spec:
        containers:
        - image: ${APP_IMAGE}
          imagePullPolicy: Always
          name: ${CI_PROJECT_PATH_SLUG}-${APP_STAGE}
          ports:
          - containerPort: 8081
            protocol: TCP
          envFrom:
          - secretRef:
              name: ${CI_PROJECT_PATH_SLUG}-${APP_STAGE}
          resources:
            limits:
              cpu: 400m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 32Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 2
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 2
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - name: config
            mountPath: /etc/jira-chat-notifier
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: config
          configMap:
            name: ${CI_PROJECT_PATH_SLUG}-${APP_STAGE}
    test: false
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${CI_ENVIRONMENT_SLUG}
    annotations:
      prometheus.io/scrape: "true"
    name: ${CI_PROJECT_PATH_SLUG}-${APP_STAGE}
  spec:
    ports:
    - name: web
      port: 8081
      protocol: TCP
      targetPort: 8081
    selector:
      deploymentconfig: ${CI_PROJECT_PATH_SLUG}-${APP_STAGE}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    name: ${CI_PROJECT_PATH_SLUG}-${APP_STAGE}
    labels:
      app: ${CI_ENVIRONMENT_SLUG}
    annotations:
      kubernetes.io/tls-acme: ${TLS_ACME}
  spec:
    host: ${URL}
    port:
      targetPort: web
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${CI_PROJECT_PATH_SLUG}-${APP_STAGE}
      weight: 100
    wildcardPolicy: None
